# Generated by Django 4.0 on 2022-01-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(max_length=122)),
                ('eventname', models.CharField(max_length=122)),
                ('location', models.CharField(max_length=15)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('deadDate', models.DateTimeField()),
                ('dec', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=122)),
                ('contactnumber', models.CharField(default='', max_length=122)),
                ('part_email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(max_length=122)),
                ('eventName', models.CharField(max_length=122)),
                ('number', models.CharField(max_length=122)),
            ],
        ),
    ]
