# Generated by Django 4.0 on 2022-01-24 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_part_part_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='part_id',
        ),
    ]
