# Generated by Django 4.0 on 2022-01-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_id',
            field=models.CharField(default='', max_length=122),
        ),
    ]
