# Generated by Django 4.0 on 2022-01-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_part_part_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='reg_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
