# Generated by Django 4.0 on 2022-01-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_part_reg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='nop',
            field=models.CharField(default='', max_length=122),
        ),
    ]
