# Generated by Django 4.0 on 2022-01-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_part_nop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='nop',
        ),
        migrations.AddField(
            model_name='event',
            name='nop',
            field=models.CharField(default='', max_length=122),
        ),
    ]
