# Generated by Django 4.0 on 2022-01-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_part_nop_event_nop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='nop',
            field=models.IntegerField(),
        ),
    ]
