# Generated by Django 4.0 on 2022-02-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_event_user_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user_event',
        ),
    ]
