# Generated by Django 4.0 on 2022-02-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_event_user_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='number',
            field=models.IntegerField(max_length=122),
        ),
    ]
