# Generated by Django 4.0 on 2022-03-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_part_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='deadDate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='host_email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='password',
        ),
        migrations.RemoveField(
            model_name='part',
            name='password',
        ),
        migrations.AlterField(
            model_name='part',
            name='number',
            field=models.IntegerField(),
        ),
    ]
