# Generated by Django 4.0 on 2022-03-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_event_deaddate_remove_event_enddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('admin', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=500)),
                ('admin_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
