# Generated by Django 4.0 on 2022-03-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_clubs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clubs',
            new_name='Club',
        ),
    ]
